
package cn.itcast.crm.ws.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import cn.itcast.crm.ws.Customer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://ws.crm.itcast.cn/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<cn.itcast.crm.ws.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaIdIsNull", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByFixedAreaIdIsNull")
    @ResponseWrapper(localName = "findByFixedAreaIdIsNullResponse", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByFixedAreaIdIsNullResponse")
    public List<Customer> findByFixedAreaIdIsNull();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByAddress", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByAddress")
    @ResponseWrapper(localName = "findByAddressResponse", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByAddressResponse")
    public String findByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.itcast.crm.ws.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByEmailAndPassword", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByEmailAndPassword")
    @ResponseWrapper(localName = "findByEmailAndPasswordResponse", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByEmailAndPasswordResponse")
    public Customer findByEmailAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.itcast.crm.ws.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephone", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByTelephone")
    @ResponseWrapper(localName = "findByTelephoneResponse", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByTelephoneResponse")
    public Customer findByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "activeEmail", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.ActiveEmail")
    @ResponseWrapper(localName = "activeEmailResponse", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.ActiveEmailResponse")
    public void activeEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.itcast.crm.ws.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephoneAndPassword", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByTelephoneAndPassword")
    @ResponseWrapper(localName = "findByTelephoneAndPasswordResponse", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByTelephoneAndPasswordResponse")
    public Customer findByTelephoneAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.AssigncustomerstodecidedzoneResponse")
    public void assigncustomerstodecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.itcast.crm.ws.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaId", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByFixedAreaId")
    @ResponseWrapper(localName = "findByFixedAreaIdResponse", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.FindByFixedAreaIdResponse")
    public List<Customer> findByFixedAreaId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://ws.crm.itcast.cn/", className = "cn.itcast.crm.ws.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

}
